# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    r_github_packages:
    - r-lib/pkgdown
    after_success:
    - Rscript -e 'covr::codecov()'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1
    r_github_packages:
    - yihui/highr@v0.7

env:
  global:
    - MAKEFLAGS="-j 2"
    - _R_CHECK_SYSTEM_CLOCK_=FALSE
