# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    env:
    - REVDEPCHECK=1
    script:
    - Rscript -e 'install.packages("devtools")'
    - git clone https://github.com/tidyverse/blob
    - git clone https://github.com/tidyverse/hms
    - git clone https://github.com/r-lib/pillar
    - Rscript -e 'remotes::install_deps("blob")'
    - Rscript -e 'remotes::install_deps("hms")'
    - Rscript -e 'remotes::install_deps("pillar")'
    - Rscript -e 'remotes::install_local(".")'
    - Rscript -e 'devtools::test("blob", reporter = c("progress", "stop"))'
    - Rscript -e 'devtools::test("hms", reporter = c("progress", "stop"))'
    - Rscript -e 'devtools::test("pillar", reporter = c("progress", "stop"))'
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
      Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.3
  - r: 3.2

env:
  global:
    - MAKEFLAGS="-j 2"
    - _R_CHECK_SYSTEM_CLOCK_=FALSE
